function save(){
  window.localStorage['Player'] = JSON.stringify(Player);
  window.s = JSON.parse(window.localStorage['Player']);
}

function deleteSave(){
  window.s = JSON.parse(window.localStorage['Player']);
  p.wins = 0;
  p.faceitWins = 0;
  p.losses = 0;
  p.faceitLosses = 0;
  p.skins = 0;
  p.elo = 0;
  p.faceitElo = 0;
  p.money = 0;
  p.mouse = 0;
  p.keyboard = 0;
  p.screen = 0;
  p.gpu = 0;
  p.cpu = 0;
  p.aim = 1;
  p.movement = 1;
  p.gameSense = 1;
  s.wins = p.wins;
  s.losses = p.losses;
  s.faceitWins = p.faceitWins;
  s.faceitLosses = p.faceitLosses;
  s.skins = p.skins;
  s.elo = p.elo;
  s.faceitElo = p.faceitElo;
  s.money = p.money;
  s.mouse = p.mouse;
  s.keyboard = p.keyboard;
  s.screen = p.screen;
  s.gpu = p.gpu;
  s.cpu = p.cpu;
  s.aim = p.aim;
  s.movement = p.movement;
  s.gameSense = p.gameSense;
  updateHTML("wins", p.wins);
  updateHTML("losses", p.losses);
  updateHTML("faceitWins", p.faceitWins);
  updateHTML("faceitLosses", p.faceitLosses);
  updateHTML("skins", p.skins);
  updateHTML("elo", p.elo);
  updateHTML("faceitElo", p.faceitElo);
  updateHTML("money", p.money);
  updateHTML("mouse", mouseName[p.mouse] + " $" + mousePrice[p.mouse]);
  updateHTML("keyboard", keyboardName[p.keyboard] + " $" + keyboardPrice[p.keyboard]);
  updateHTML("screen", screenName[p.screen] + ", $" + screenPrice[p.screen] + ", " + screenRefreshRate[p.screen] + "hz, " + screenInches[p.screen] + "hz");
  updateHTML("gpu", gpuName[p.gpu] + " $" + gpuPrice[p.gpu]);
  updateHTML("cpu", cpuName[p.cpu] + " $" + cpuPrice[p.cpu]);
  updateHTML("aim", p.aim);
  updateHTML("gameSense", p.gameSense);
  updateHTML("movement", p.movement);
  updateStats();
  checkRank();
  checkFaceitRank();
}

function load(){
  window.s = JSON.parse(window.localStorage['Player']);
  p.wins = s.wins;
  p.losses = s.losses;
  p.faceitWins = s.faceitWins;
  p.faceitLosses = s.faceitLosses;
  p.skins = s.skins;
  p.elo = s.elo;
  p.faceitElo = s.faceitElo;
  p.money = s.money;
  p.mouse = s.mouse;
  p.keyboard = s.keyboard;
  p.screen = s.screen;
  p.gpu = s.gpu;
  p.cpu = s.cpu;
  p.aim = s.aim;
  p.movement = s.movement;
  p.gameSense = s.gameSense;
  updateHTML("wins", p.wins);
  updateHTML("losses", p.losses);
  updateHTML("faceitWins", p.faceitWins);
  updateHTML("faceitLosses", p.faceitLosses);
  updateHTML("skins", p.skins);
  updateHTML("elo", p.elo);
  updateHTML("faceitElo", p.faceitElo);
  updateHTML("money", p.money.toFixed(2));
  updateHTML("mouse", mouseName[p.mouse] + " $" + mousePrice[p.mouse]);
  updateHTML("keyboard", keyboardName[p.keyboard] + " $" + keyboardPrice[p.keyboard]);
  updateHTML("screen", screenName[p.screen] + ", $" + screenPrice[p.screen] + ", " + screenRefreshRate[p.screen] + "hz, " + screenInches[p.screen] + "hz");
  updateHTML("gpu", gpuName[p.gpu] + " $" + gpuPrice[p.gpu]);
  updateHTML("cpu", cpuName[p.cpu] + " $" + cpuPrice[p.cpu]);
  updateHTML("aim", p.aim);
  updateHTML("gameSense", p.gameSense);
  updateHTML("movement", p.movement);
};
